approvals/urls.py
from django.conf.urls import url
from approvals import views

urlpatterns = [
                  url(r'^approvals/$', views.ApprovalList.as_view(), name='approval_list'),
                  url(r'^approvals/(?P<pk>\d+)/$', views.ApprovalDetails.as_view(), name='approval_detail'),
                  url(r'^approvals/(?P<pk>\d+)/change/(?P<status>\w+)/$', views.ApprovalStatusChange.as_view(), name='approval_status_change'),
                  url(r'^approvals/(?P<pk>\d+)/actions/$', views.ApprovalActions.as_view(), name='approval_actions'),
                  url(r'^approvals/(?P<pk>\d+)/comms-create/$', views.ApprovalCommsCreate.as_view(), name='approvals_comms_create'),
                  url(r'^approvals/(?P<pk>\d+)/comms/$', views.ApprovalComms.as_view(), name='approvals_comms'),
                  url(r'^approvals/viewpdf-(?P<approval_id>\d+).pdf$', views.getPDF, name='approvals_view_pdf'),
              ]

statdev/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import login
from ledger.accounts.views import logoutUser

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login, name='login', kwargs={'template_name': 'login.html'}),
    url(r'^logout/$', logoutUser, name='logout' ),
    url(r'^', include('applications.urls')),
    url(r'^', include('approvals.urls')),
    url(r'^', include('public.urls')),
    url(r'^ledger/', include('ledger.accounts.urls', namespace='accounts')),
    url(r'^ledger/', include('social_django.urls', namespace='social')),
    #url(r'^', include('approvals.urls'))
]

if settings.DEBUG:
    from django.views.static import serve
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

actions/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from model_utils import Choices


@python_2_unicode_compatible
class Action(models.Model):
    """This model represents an action performed to or with another object.
    It uses a generic foreign key to allow any other object to be linked to
    an action.
    """
    ACTION_CATEGORY_CHOICES = Choices(
        (1, 'communicate', ('Communicate')),
        (2, 'assign', ('Assign')),
        (3, 'refer', ('Refer')),
        (4, 'issue', ('Issue')),
        (5, 'decline', ('Decline')),
        (6, 'publish', ('Publish')),
        (7, 'lodge', ('Lodge')),
        (8, 'action', ('Next Step')),
        (9, 'change', ('Change')),
        (10, 'create',('Create'))
        # TODO: Compliance request
        # TODO: Request/add/remove delegate
    )
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()
    action = models.CharField(max_length=512)
    timestamp = models.DateTimeField(auto_now_add=True, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL)
    category = models.IntegerField(choices=ACTION_CATEGORY_CHOICES, null=True, blank=True)

    def __str__(self):
        return '{}: {}'.format(self.content_object, self.action)

approvals/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from applications.models import Application, Record
from django.conf import settings
from django.db import models
from model_utils import Choices
from applications.models import Application
from ledger.accounts.models import Organisation

@python_2_unicode_compatible
class Approval(models.Model):
     """This model represents an approvals by a customer to P&W for a single
     permit, licence/permit, part 5, etc.
     """

     APPROVAL_STATE_CHOICES = Choices(
        (1, 'current', ('Current')),
        (2, 'expired', ('Expired')),
        (3, 'cancelled', ('Cancelled')),
        (4, 'surrendered', ('Surrendered')),
        (5, 'suspended', ('Suspended')),
        (6, 'reinstate', ('Reinstate'))
     )

     app_type = models.IntegerField(choices=Application.APP_TYPE_CHOICES)
     title = models.CharField(max_length=254)
     applicant = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.PROTECT, related_name='applicant_holder')
     organisation = models.ForeignKey(Organisation, blank=True, null=True, on_delete=models.PROTECT)
     application = models.ForeignKey(Application, on_delete=models.CASCADE,null=True, blank=True, related_name='application') 
     issue_date = models.DateField(null=True, blank=True, auto_now_add=True)
     start_date = models.DateField(null=True, blank=True)
     expiry_date = models.DateField(null=True, blank=True)
     status = models.IntegerField(choices=APPROVAL_STATE_CHOICES) 
     approval_document = models.ForeignKey(Record, null=True, blank=True, related_name='approval_document')
     suspend_from_date = models.DateField(null=True, blank=True)
     suspend_to_date = models.DateField(null=True, blank=True)
     ammendment_application  = models.ForeignKey(Application, on_delete=models.CASCADE,null=True, blank=True, related_name='ammendment_application')
     reinstate_date = models.DateField(null=True, blank=True)
     cancellation_date = models.DateField(null=True, blank=True)
     surrender_date = models.DateField(null=True, blank=True)
     details = models.TextField(null=True, blank=True)

     def __str__(self):
        return 'Approvals {}: {} - {} ({})'.format(
            self.pk, self.get_app_type_display(), self.title, self.get_status_display())

        return self.name


class CommunicationApproval(models.Model):
    """This model represents the communication model
    """
    COMM_TYPE = Choices(
        (0, 'none', ('None')),
        (1, 'phone', ('Phone')),
        (2, 'email', ('Email')),
        (3, 'mail', ('Mail')),
        (4, 'system', ('System'))
    )

    approval = models.ForeignKey(Approval, on_delete=models.PROTECT)
    comms_to = models.CharField(max_length=256, null=True, blank=True)
    comms_from = models.CharField(max_length=256, null=True, blank=True)
    subject = models.CharField(max_length=256, null=True, blank=True)
    comms_type = models.IntegerField(choices=COMM_TYPE, default=COMM_TYPE.none )
    details = models.TextField(blank=True, null=True)
    records = models.ManyToManyField(Record, blank=True, related_name='communication_approvals_docs')
    state = models.IntegerField(blank=True, null=True)  # move to foreign key once APP_STATE_CHOICES becomes a model
    created = models.DateTimeField(auto_now_add=True)

 

approvals/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, UpdateView, DetailView, CreateView
from django.core.urlresolvers import reverse
from .models import Approval as ApprovalModel, CommunicationApproval 
from django.db.models import Q
from django.contrib.auth.models import Group
from applications.utils import get_query
from . import forms as apps_forms
from actions.models import Action
from django.contrib.contenttypes.models import ContentType
from applications.models import Application, Record, Delegate
from applications.validationchecks import Attachment_Extension_Check
from django.http import HttpResponse, HttpResponseRedirect
from statdev.context_processors import template_context
from django.contrib import messages
from applications.views_pdf import PDFtool
import os.path
import os 

class ApprovalList(ListView):
    model = ApprovalModel

    def get(self, request, *args, **kwargs):
        context_processor = template_context(self.request)
        staff = context_processor['staff']
        if staff == True:
           donothing =""
        else:
           messages.error(self.request, 'Forbidden from viewing this page.')
           return HttpResponseRedirect("/")
        return super(ApprovalList, self).get(request, *args, **kwargs)

    def get_queryset(self):
        qs = super(ApprovalList, self).get_queryset()

        # Did we pass in a search string? If so, filter the queryset and return
        # it.
        if 'q' in self.request.GET and self.request.GET['q']:
            query_str = self.request.GET['q']
            # Replace single-quotes with double-quotes
            query_str = query_str.replace("'", r'"')
            # Filter by pk, title, applicant__email, organisation__name,
            # assignee__email
            query = get_query(
                query_str, ['pk', 'title', 'applicant__email'])
            qs = qs.filter(query).distinct()
        return qs

    def get_context_data(self, **kwargs):
        context = super(ApprovalList, self).get_context_data(**kwargs)

        APP_TYPE_CHOICES = []
        APP_TYPE_CHOICES_IDS = []
        for i in Application.APP_TYPE_CHOICES:
            if i[0] in [4,5,6,7,8,9,10,11]:
               skip = 'yes'
            else:
               APP_TYPE_CHOICES.append(i)
               APP_TYPE_CHOICES_IDS.append(i[0])
        context['app_apptypes']= APP_TYPE_CHOICES


        if 'action' in self.request.GET and self.request.GET['action']:
            query_str = self.request.GET['q']
            query_obj = Q(pk__contains=query_str) | Q(title__icontains=query_str) | Q(applicant__email__icontains=query_str)

            if self.request.GET['apptype'] != '':
                query_obj &= Q(app_type=int(self.request.GET['apptype']))
            else:
                query_obj &= Q(app_type__in=APP_TYPE_CHOICES_IDS)

            if self.request.GET['applicant'] != '':
                query_obj &= Q(applicant=int(self.request.GET['applicant']))
            if self.request.GET['appstatus'] != '':
                query_obj &= Q(status=int(self.request.GET['appstatus']))

            objlist = ApprovalModel.objects.filter(query_obj)
            context['query_string'] = self.request.GET['q']

            if self.request.GET['apptype'] != '':
                 context['apptype'] = int(self.request.GET['apptype'])
            if self.request.GET['applicant'] != '':
                 context['applicant'] = int(self.request.GET['applicant'])
            if 'appstatus' in self.request.GET:
                if self.request.GET['appstatus'] != '':
                    context['appstatus'] = int(self.request.GET['appstatus'])


#        if 'q' in self.request.GET and self.request.GET['q']:
 #           query_str = self.request.GET['q']
  #          objlist = ApprovalModel.objects.filter(Q(pk__contains=query_str) | Q(title__icontains=query_str) | Q(applicant__email__icontains=query_str))
        else:
            objlist = ApprovalModel.objects.filter()
        usergroups = self.request.user.groups.all()

        context['app_list'] = []
        context['app_applicants'] = {}
        context['app_applicants_list'] = []
        context['app_appstatus'] = list(ApprovalModel.APPROVAL_STATE_CHOICES)

        for app in objlist.order_by('title'):
            row = {}
            row['app'] = app
        #    if app.group is not None:

            if app.applicant:
                if app.applicant.id in context['app_applicants']:
                    donothing = ''
                else:
                    context['app_applicants'][app.applicant.id] = app.applicant.first_name + ' ' + app.applicant.last_name
                    context['app_applicants_list'].append({"id": app.applicant.id, "name": app.applicant.first_name + ' ' + app.applicant.last_name})


            context['app_list'].append(row)


#       context['app_list'] = context['app_list'].order_by('title')

        # TODO: any restrictions on who can create new applications?
        processor = Group.objects.get(name='Processor')

        # Rule: admin officers may self-assign applications.
        if processor in self.request.user.groups.all() or self.request.user.is_superuser:
            context['may_assign_processor'] = True

        return context

class ApprovalDetails(LoginRequiredMixin,DetailView):
    model = ApprovalModel

    def get_context_data(self, **kwargs):
        context = super(ApprovalDetails, self).get_context_data(**kwargs)
        app = self.get_object()
        context_processor = template_context(self.request)
        context['admin_staff'] = context_processor['admin_staff']
        return context

class ApprovalStatusChange(LoginRequiredMixin,UpdateView):
    model = ApprovalModel
    form_class = apps_forms.ApprovalChangeStatus
    template_name = 'applications/application_form.html'

    def get(self, request, *args, **kwargs):
        modelobject = self.get_object()
        return super(ApprovalStatusChange, self).get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('approval_list', args=())

    def get_context_data(self, **kwargs):
        context = super(ApprovalStatusChange,self).get_context_data(**kwargs)
        self.object = self.get_object()
        context['title'] = self.object.title
        return context

    def get_initial(self):
        initial = super(ApprovalStatusChange, self).get_initial()
        approval = self.get_object()
        status = self.kwargs['status']
        initial['status'] = ApprovalModel.APPROVAL_STATE_CHOICES.__getattr__(status)
        return initial

    def post(self, request, *args, **kwargs):
        #        self.initial = self.get_initial()
        self.object = self.get_object()
        self.object.status = 2
        #print self.initial['status']
        if request.POST.get('cancel'):
            app = Application.objects.get(pk=self.kwargs['application'])
            return HttpResponseRedirect(app.get_absolute_url())
        return super(ApprovalStatusChange, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        
        self.object = form.save(commit=False)
        app = self.get_object()
        status = self.kwargs['status']
        self.object.status = ApprovalModel.APPROVAL_STATE_CHOICES.__getattr__(status)
        self.object.save()

        action = Action(
            content_object=app, category=Action.ACTION_CATEGORY_CHOICES.change,
            user=self.request.user, action='Approval Change')
        action.save()

        return super(ApprovalStatusChange, self).form_valid(form)

class ApprovalActions(DetailView):
    model = ApprovalModel
    template_name = 'approvals/approvals_actions.html'

    def get(self, request, *args, **kwargs):
        context_processor = template_context(self.request)
        admin_staff = context_processor['admin_staff']
        if admin_staff == True:
           donothing =""
        else:
           messages.error(self.request, 'Forbidden from viewing this page.')
           return HttpResponseRedirect("/")
        return super(ApprovalActions, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ApprovalActions, self).get_context_data(**kwargs)
        app = self.get_object()
        # TODO: define a GenericRelation field on the Application model.
        context['actions'] = Action.objects.filter(
            content_type=ContentType.objects.get_for_model(app), object_id=app.pk).order_by('-timestamp')
        return context

class ApprovalCommsCreate(CreateView):
    model = CommunicationApproval
    form_class = apps_forms.CommunicationCreateForm
    template_name = 'applications/application_comms_create.html'

    def get_context_data(self, **kwargs):
        context = super(ApprovalCommsCreate, self).get_context_data(**kwargs)
        context['page_heading'] = 'Create new communication'
        return context

    def get_initial(self):
        initial = {}
        initial['application'] = self.kwargs['pk']
        return initial

    def get_form_kwargs(self):
        kwargs = super(ApprovalCommsCreate, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def post(self, request, *args, **kwargs):
        if request.POST.get('cancel'):
            return HttpResponseRedirect(reverse('home_page'))
        return super(ApprovalCommsCreate, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        """Override form_valid to set the assignee as the object creator.
        """
        self.object = form.save(commit=False)
        app_id = self.kwargs['pk']

        approval = ApprovalModel.objects.get(id=app_id)
        self.object.approval = approval
        self.object.save()

        if self.request.FILES.get('records'):
            if Attachment_Extension_Check('multi', self.request.FILES.getlist('records'), None) is False:

approvals/templates/approvals/approval_comms.html
{% extends "base_statdev.html" %}

{% block page_content_inner %}
<div class="container-fluid">
    <div class="row">
        <h1>Communication for {{ object.application.get_app_type_display }} - {{ object.pk }}</h1>
        <p><a href="{% url 'approval_detail' object.pk %}">Return to approval details</a></p>
        <h2>communication log</h2>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Date & time</th>
                    <th>Comms Type</th>
                    <th>To</th>
                    <th>From</th>
                    <th>Subject</th>
                    <th>Details</th>
                    <th>Documents</th>
                </tr>
            </thead>
         {% if communications.exists %}
            <tbody>
                {% for communication in communications %}
                <tr>
                    <td>{{ communication.created|date:"d-M-Y H:i" }}</td>
                    <td>{{ communication.get_comms_type_display }}</td>
                    <td>{{ communication.comms_to }}</td>
                    <td>{{ communication.comms_from }}</td>
                    <td>{{ communication.subject }}</td>
                    <td>{{ communication.details }}</td>
                    <td>
			{% if communication.records.exists %}
                        {% for doc in communication.records.all %}
                            <div class="col-sm-12 col-md-12 col-lg-12"><A HREF='/media/{{ doc.upload }}'>{{ doc.name }}</A></div>
                        {% endfor %}
                        {% endif %}
                        </td>
                </tr>
                {% endfor %}
         {% endif %}
        </table>
        <p><a href="{% url 'approval_detail' object.pk %}">Return to approval details</a></p>
    </div>
</div>
{% endblock page_content_inner %}

approvals/templates/approvals/approval_list.html
{% extends "base_statdev.html" %}
{% load static %}
{% block page_content_inner %}

<div class="panel panel-default">

	<div class="panel-heading" role="tab" id="title_heading">
		<h3 class="panel-title">
			<a role="button" data-toggle="collapse" href="#application_list_collapse" aria-expanded="false" aria-controls="application_list_collapse">
				Approvals
                                <span class="glyphicon glyphicon-chevron-down collapse-glyph"></span>
			</a>
		</h3>
	</div>

	<div class="panel-collapse collapse in" id="application_list_collapse" role="tabpanel" aria-labelledby="application_list_heading">
		<div class="panel-body">
			<div class="row">
				<form action="" method="get">
					<div class="col-sm-12 col-lg-12">
						<input type='hidden' name='action' value='search'>
						<!-- RES -->
						<div class="col-sm-12 col-lg-3">
							<div class="col-sm-12 col-lg-12">
								<label>Type:</label>
							</div>
							<div class="col-sm-12 col-lg-12">
								<select class="select form-control" id="id_apptype" name="apptype">
									<option value="" >All</option>
									{% for at in app_apptypes %}
									{% if apptype == at.0 %}
									<option selected="selected" value="{{ at.0 }}">{{ at.1 }}</option>
									{% else %}
									<option value="{{ at.0 }}">{{ at.1 }}</option>
									{% endif %}

									{% endfor %}
								</select>
							</div>
						</div>
						<div class="col-sm-12 col-lg-3">
							<div class="col-sm-12 col-lg-12">
								<label>Holder:</label>
							</div>
							<div class="col-sm-12 col-lg-12">
								<select class="select form-control" id="id_applicant" name="applicant">
									<option value="" selected="selected">All</option>
									{% for person in app_applicants_list|dictsort:'name' %}
									{% if applicant == person.id %}
									<option selected="selected" value="{{ person.id }}">{{ person.name }}</option>
									{% else %}
									<option value="{{ person.id }}">{{ person.name }}</option>
									{% endif %}
									{% endfor %}
								</select>
							</div>
						</div>

						<div class="col-sm-12 col-lg-3">
							<div class="col-sm-12 col-lg-12">
								<label>Status:</label>
							</div>
							<div class="col-sm-12 col-lg-12">
								<select class="select form-control" id="id_appstatus" name="appstatus">
									<option value="" selected="selected">All</option>
									{% for at in app_appstatus %}
									{% if appstatus == at.0 %}
									<option selected value="{{ at.0 }}">{{ at.1 }}</option>
									{% else %}
									<option value="{{ at.0 }}">{{ at.1 }}</option>
									{% endif %}
									{% endfor %}
								</select>
							</div>
						</div>
					</div>
					<div class="col-sm-12 col-lg-12">
						<div class="col-sm-12 col-lg-9">

							<div class="col-sm-12 col-lg-12">
								<label for="search_field">Keywords:</label>
							</div>
							<div class="col-sm-12 col-lg-12">
								<input id="search_field" type="text" class="form-control" name="q" placeholder="Enter Keywords" value="{{ query_string }}">
							</div>
						</div>

						 <div class="col-sm-12 col-lg-3">
		                    <div class="col-sm-12 col-lg-12">
        		                <input type="submit" name="search" value="Search" class="btn btn-primary btn-lg" id="submit-id-save">
                		    </div>
		                </div>

					</div>
				</form>
			</div>

			<br>
			<div class="row">
				<div class="col-xs-12">
					<table id='approvals-table' class="table table-striped table-bordered table-condensed">
						<thead>
							<tr>
								<th>Approval no.</th>
								<th>Type</th>
								<th>Title</th>
								<th>Holder</th>
								<th>Status</th>
								<th>Start Date</th>
								<th>Expiry Date</th>
								<th>Approval</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>

							{% for app_obj in app_list %}
							<tr>
								<td><a href="{% url 'approval_detail' app_obj.app.pk %}">AP-{{ app_obj.app.pk }}</a></td>
								<td>{{ app_obj.app.get_app_type_display }}</td>
								<td>{{ app_obj.app.title }}</td>
								<td>    {% if app_obj.app.organisation %}
					                                 {{ app_obj.app.organisation }}
        					                        {% else %}
                                					 {{ app_obj.app.applicant.get_full_name }}
					                                {% endif %}
								</td>
								<td>{{ app_obj.app.get_status_display }}</td>
								<td>{{ app_obj.app.start_date|date:"d-M-Y" }}</td>
								<td>{{ app_obj.app.expiry_date|date:"d-M-Y" }}</td>
								<td align='center' valign='center'><A HREF='{% url "approvals_view_pdf" app_obj.app.pk %}'><img src='{% static "images/pdf.png" %}' title="Click to Download PDF"></A></td>
								<td>
									<ul class="nav navbar-nav">
										<li class="dropdown">
											<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Actions<span class="caret"></span></a>
											<ul class="dropdown-menu" role="menu">
                                                                                                <li><a href="{% url 'approval_detail' app_obj.app.pk %}">View Approval</a></li>
                                                                                                <li><a href="{% url 'application_detail' app_obj.app.application.id %}">View Application</a></li>
                                                                                                {% if app_obj.app.status == 1 %}
												{% if app_obj.app.app_type == 3 %}
												<!-- Add Logic to check if ammendment request has been completed -->
												{% if app_obj.app.ammendment_application %}
												{% if app_obj.app.ammendment_application.get_state_display == "Approved" %}
												<li><a href="{% url 'application_change' app_obj.app.pk 'amend' %}">Amend</a></li>
												{% endif %}
												{% endif %}
												{% else %}
												<li><a href="{% url 'application_change' app_obj.app.pk 'amend' %}">Amend</a></li>
												{% endif %}
												<li><a href="{% url 'approval_status_change' app_obj.app.pk 'cancelled' %}" title="Cancel">Cancel</a></li>
												<li><a href="{% url 'approval_status_change' app_obj.app.pk 'expired' %}" title="Expire">Expire</a></li>
												<li><a href="{% url 'approval_status_change' app_obj.app.pk 'suspended' %}" title="Suspend">Suspend</a></li>
												<li><a href="{% url 'approval_status_change' app_obj.app.pk 'surrendered' %}" title="Surrendered">Surrendered</a></li>
												
												{% if app_obj.app.app_type == 3 %}
												{% else %}
												<li><a href="/">Renew</a></li>

												<li><a href="/" title="Administration">Renewal Notice</a></li>
												{% if app_obj.app.app_type == 3 %}
												<li><a href="{% url 'application_change' app_obj.app.pk 'requestamendment' %}">Request Amendment</a></li>
												{% endif %}
												{% endif %}
												{% endif %}
                                                                                                {% if app_obj.app.status == 5 or app_obj.app.status == 3 %}
													<li><a href="{% url 'approval_status_change' app_obj.app.pk 'reinstate' %}" title="Reinstate">Reinstate</a></li>
												{% endif %}

											</ul>   
										</li>
									</ul>
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>

		</div>
	</div>
</div>
<script>

function loadApprovalTable() { 
    $('#approvals-table').dataTable({searching: false, paging: true, "pageLength": 25,"order": [[ 0, "desc" ]],
     columnDefs: [
       { type: 'natural-nohtml', targets: 0 }, { type: 'date-dd-mmm-yyyy', targets: 5 }, { type: 'date-dd-mmm-yyyy', targets: 6 }, { 'bSortable': false, 'aTargets':  8 }
     ]

});
}

window.onload= function() {
    loadApprovalTable();
}

</script>

{% endblock %}

approvals/templates/approvals/approval_side_menu.html
<div class="col-sm-4 col-md-3 col-lg-2">
{% if admin_staff == True %}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Actions</h3>
    </div>
    <div class="panel-body">
        <h5>Communications</h5>
        <p><a href="{% url 'approvals_comms' object.pk %}">Show</a> | <a href="{% url 'approvals_comms_create' object.pk %}">Add Entry</a></p>
        <hr />
        <h5>Actions</h5>
        <ul>
        <li><a href="{% url 'approval_actions' object.pk %}">Action Log</a></li>
        </ul>
        <ul>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Workflow</h3>
    </div>
    <div class="panel-body">
        <label>Status</Label>
        <p>{{ object.get_status_display }}</p>
        <hr />
	<label>Assigned To</Label>
	<p></p>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Related Approval</h3>
    </div>
    <div class="panel-body">
        <label>Section 84</Label>
        <p>48613</p>
    </div>
</div>

{% endif %}
</div>

approvals/templates/approvals/approvals_actions.html
{% extends "base_statdev.html" %}

{% block page_content_inner %}
<div class="container-fluid">
    <div class="row">
        <h1>Approval for {{ object.get_app_type_display }} - {{ object.pk }}</h1>
        <p><a href="{% url 'approval_detail' object.pk %}">Return to approval details</a></p>
        <h2>Action/communication log</h2>
        {% if actions %}
        <table id='action-log-table' class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Date & time</th>
                    <th>Category</th>
                    <th>User</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for action in actions %}
                <tr>
                    <td>{{ action.timestamp|date:"d-M-Y H:i" }}</td>
                    <td>{% if action.category %}{{ action.get_category_display }}{% endif %}</td>
                    <td>{% if action.user %}{{ action.user.get_full_name }}{% else %}System{% endif %}</td>
                    <td>{{ action.action }}</td>
                </tr>
                {% endfor %}
        </table>
        <p><a href="{% url 'approval_detail' object.pk %}">Return to approval details</a></p>
        {% else %}
        <p>No actions recorded.</p>
        {% endif %}
    </div>
</div>

<script>
function loadTableGrid() {
        $('#action-log-table').dataTable({searching: true, paging: true, "pageLength": 25});
}
window.onload= function() {
        loadTableGrid();
}
</script>


{% endblock page_content_inner %}